import { jsPDF } from 'jspdf';
import { ModuleSRS } from '@/data/srs/rosterSRS';

// Color palette
const COLORS = {
  primary: [30, 64, 175] as [number, number, number],       // Blue-700
  primaryLight: [219, 234, 254] as [number, number, number], // Blue-100
  dark: [15, 23, 42] as [number, number, number],            // Slate-900
  text: [51, 65, 85] as [number, number, number],            // Slate-600
  muted: [100, 116, 139] as [number, number, number],        // Slate-500
  border: [203, 213, 225] as [number, number, number],       // Slate-300
  bg: [248, 250, 252] as [number, number, number],           // Slate-50
  white: [255, 255, 255] as [number, number, number],
  critical: [220, 38, 38] as [number, number, number],
  high: [234, 88, 12] as [number, number, number],
  medium: [202, 138, 4] as [number, number, number],
  low: [22, 163, 74] as [number, number, number],
  accent: [79, 70, 229] as [number, number, number],         // Indigo-600
};

const MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function getPriorityColor(priority: string): [number, number, number] {
  switch (priority) {
    case 'critical': return COLORS.critical;
    case 'high': return COLORS.high;
    case 'medium': return COLORS.medium;
    case 'low': return COLORS.low;
    default: return COLORS.muted;
  }
}

class SRSPdfBuilder {
  private doc: jsPDF;
  private y: number = 0;
  private pageNum: number = 0;
  private totalPages: number = 0;
  private moduleName: string = '';

  constructor() {
    this.doc = new jsPDF('p', 'mm', 'a4');
    this.y = MARGIN;
    this.pageNum = 1;
  }

  private checkPageBreak(neededHeight: number) {
    if (this.y + neededHeight > 277) {
      this.addPage();
    }
  }

  private addPage() {
    this.doc.addPage();
    this.pageNum++;
    this.y = MARGIN;
    this.drawPageHeader();
  }

  private drawPageHeader() {
    // Top accent line
    this.doc.setFillColor(...COLORS.primary);
    this.doc.rect(0, 0, PAGE_WIDTH, 3, 'F');
    
    // Module name in header
    this.doc.setFontSize(8);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text(`Software Requirements Specification — ${this.moduleName}`, MARGIN, 10);
    
    // Line under header
    this.doc.setDrawColor(...COLORS.border);
    this.doc.setLineWidth(0.3);
    this.doc.line(MARGIN, 12, PAGE_WIDTH - MARGIN, 12);
    
    this.y = 18;
  }

  private drawFooters() {
    const totalPages = this.doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(`Page ${i} of ${totalPages}`, PAGE_WIDTH - MARGIN, 290, { align: 'right' });
      this.doc.text('Generated by RosteredAI', MARGIN, 290);
      // Bottom accent line
      this.doc.setFillColor(...COLORS.primary);
      this.doc.rect(0, 294, PAGE_WIDTH, 3, 'F');
    }
  }

  private sectionTitle(title: string, icon?: string) {
    this.checkPageBreak(18);
    this.y += 6;
    
    // Section background bar
    this.doc.setFillColor(...COLORS.primaryLight);
    this.doc.roundedRect(MARGIN, this.y - 4, CONTENT_WIDTH, 10, 2, 2, 'F');
    
    // Left accent
    this.doc.setFillColor(...COLORS.primary);
    this.doc.rect(MARGIN, this.y - 4, 3, 10, 'F');
    
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...COLORS.primary);
    this.doc.text(`${icon ? icon + '  ' : ''}${title}`, MARGIN + 6, this.y + 3);
    this.y += 12;
  }

  private subSectionTitle(title: string) {
    this.checkPageBreak(12);
    this.y += 3;
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...COLORS.dark);
    this.doc.text(title, MARGIN + 2, this.y);
    this.y += 5;
  }

  private bodyText(text: string, indent: number = 0) {
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.text);
    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH - indent);
    for (const line of lines) {
      this.checkPageBreak(5);
      this.doc.text(line, MARGIN + indent, this.y);
      this.y += 4.2;
    }
  }

  private bulletList(items: string[], indent: number = 4) {
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.text);
    for (const item of items) {
      const lines = this.doc.splitTextToSize(item, CONTENT_WIDTH - indent - 5);
      this.checkPageBreak(lines.length * 4.2 + 1);
      // Bullet dot
      this.doc.setFillColor(...COLORS.primary);
      this.doc.circle(MARGIN + indent, this.y - 1, 0.8, 'F');
      for (let i = 0; i < lines.length; i++) {
        this.doc.text(lines[i], MARGIN + indent + 3, this.y);
        this.y += 4.2;
      }
    }
  }

  private numberedList(items: string[], indent: number = 4) {
    this.doc.setFontSize(9);
    for (let idx = 0; idx < items.length; idx++) {
      const lines = this.doc.splitTextToSize(items[idx], CONTENT_WIDTH - indent - 8);
      this.checkPageBreak(lines.length * 4.2 + 1);
      
      // Number circle
      this.doc.setFillColor(...COLORS.primary);
      this.doc.circle(MARGIN + indent + 2, this.y - 1, 2.5, 'F');
      this.doc.setFontSize(7);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.white);
      this.doc.text(`${idx + 1}`, MARGIN + indent + 2, this.y, { align: 'center' });
      
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      for (let i = 0; i < lines.length; i++) {
        this.doc.text(lines[i], MARGIN + indent + 7, this.y);
        this.y += 4.2;
      }
    }
  }

  private drawPriorityBadge(priority: string, x: number, y: number) {
    const color = getPriorityColor(priority);
    const width = this.doc.getTextWidth(priority.toUpperCase()) + 6;
    this.doc.setFillColor(...color);
    this.doc.roundedRect(x, y - 3.5, width, 5, 1.5, 1.5, 'F');
    this.doc.setFontSize(7);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...COLORS.white);
    this.doc.text(priority.toUpperCase(), x + 3, y, );
  }

  private drawCoverPage(srs: ModuleSRS) {
    // Full-page gradient simulation
    this.doc.setFillColor(...COLORS.primary);
    this.doc.rect(0, 0, PAGE_WIDTH, 297, 'F');
    
    // White content area
    this.doc.setFillColor(...COLORS.white);
    this.doc.roundedRect(15, 40, 180, 200, 4, 4, 'F');
    
    // Top decorative bar
    this.doc.setFillColor(...COLORS.accent);
    this.doc.rect(15, 40, 180, 6, 'F');
    
    // Module name
    this.doc.setFontSize(32);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...COLORS.dark);
    const titleLines = this.doc.splitTextToSize(srs.moduleName, 160);
    let titleY = 75;
    for (const line of titleLines) {
      this.doc.text(line, PAGE_WIDTH / 2, titleY, { align: 'center' });
      titleY += 14;
    }
    
    // Subtitle
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.primary);
    this.doc.text('Software Requirements Specification', PAGE_WIDTH / 2, titleY + 5, { align: 'center' });
    
    // Divider
    this.doc.setDrawColor(...COLORS.border);
    this.doc.setLineWidth(0.5);
    this.doc.line(60, titleY + 15, 150, titleY + 15);
    
    // Meta info
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.muted);
    const metaY = titleY + 28;
    this.doc.text(`Version ${srs.version}`, PAGE_WIDTH / 2, metaY, { align: 'center' });
    this.doc.text(`Last Updated: ${srs.lastUpdated}`, PAGE_WIDTH / 2, metaY + 7, { align: 'center' });
    this.doc.text(`User Stories: ${srs.userStories.length}`, PAGE_WIDTH / 2, metaY + 14, { align: 'center' });
    this.doc.text(`Table Specifications: ${srs.tableSpecs.length}`, PAGE_WIDTH / 2, metaY + 21, { align: 'center' });
    this.doc.text(`Business Rules: ${srs.businessRules.length}`, PAGE_WIDTH / 2, metaY + 28, { align: 'center' });
    
    // Stats boxes at bottom
    const statsY = metaY + 45;
    const boxWidth = 40;
    const stats = [
      { label: 'User Stories', value: `${srs.userStories.length}` },
      { label: 'Tables', value: `${srs.tableSpecs.length}` },
      { label: 'Rules', value: `${srs.businessRules.length}` },
      { label: 'Integrations', value: `${srs.integrations.length}` },
    ];
    const startX = (PAGE_WIDTH - (stats.length * boxWidth + (stats.length - 1) * 5)) / 2;
    stats.forEach((stat, i) => {
      const x = startX + i * (boxWidth + 5);
      this.doc.setFillColor(...COLORS.bg);
      this.doc.roundedRect(x, statsY, boxWidth, 22, 2, 2, 'F');
      this.doc.setFontSize(16);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      this.doc.text(stat.value, x + boxWidth / 2, statsY + 10, { align: 'center' });
      this.doc.setFontSize(7);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(stat.label, x + boxWidth / 2, statsY + 17, { align: 'center' });
    });
    
    // Footer on cover
    this.doc.setFontSize(9);
    this.doc.setTextColor(...COLORS.white);
    this.doc.text('Generated by RosteredAI', PAGE_WIDTH / 2, 260, { align: 'center' });
    this.doc.text(new Date().toLocaleDateString('en-AU', { year: 'numeric', month: 'long', day: 'numeric' }), PAGE_WIDTH / 2, 267, { align: 'center' });
  }

  private renderTableOfContents(srs: ModuleSRS) {
    this.addPage();
    this.sectionTitle('Table of Contents');
    this.y += 2;
    
    const tocItems = [
      '1. Overview & Objectives',
      '2. Scope',
      '3. Actors & Permissions',
      `4. User Stories (${srs.userStories.length})`,
      `5. Table Specifications (${srs.tableSpecs.length})`,
      `6. Business Rules (${srs.businessRules.length})`,
      `7. Integrations (${srs.integrations.length})`,
      '8. Non-Functional Requirements',
    ];
    
    this.doc.setFontSize(10);
    for (const item of tocItems) {
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.dark);
      this.doc.text(item, MARGIN + 4, this.y);
      // Dotted line
      this.doc.setDrawColor(...COLORS.border);
      this.doc.setLineDashPattern([1, 1], 0);
      const textWidth = this.doc.getTextWidth(item);
      this.doc.line(MARGIN + 6 + textWidth, this.y - 0.5, PAGE_WIDTH - MARGIN, this.y - 0.5);
      this.doc.setLineDashPattern([], 0);
      this.y += 7;
    }
  }

  private renderOverview(srs: ModuleSRS) {
    this.addPage();
    this.sectionTitle('1. Overview & Objectives');
    this.bodyText(srs.overview);
    this.y += 4;
    
    this.subSectionTitle('Objectives');
    this.bulletList(srs.objectives);
  }

  private renderScope(srs: ModuleSRS) {
    this.y += 4;
    this.sectionTitle('2. Scope');
    
    this.subSectionTitle('In Scope');
    this.bulletList(srs.scope);
    
    if (srs.outOfScope.length > 0) {
      this.y += 2;
      this.subSectionTitle('Out of Scope');
      this.bulletList(srs.outOfScope);
    }
  }

  private renderActors(srs: ModuleSRS) {
    this.sectionTitle('3. Actors & Permissions');
    
    for (const actor of srs.actors) {
      this.checkPageBreak(20);
      // Actor card
      this.doc.setFillColor(...COLORS.bg);
      const cardHeight = 8 + actor.permissions.length * 4.2;
      this.doc.roundedRect(MARGIN + 2, this.y - 2, CONTENT_WIDTH - 4, Math.min(cardHeight, 50), 2, 2, 'F');
      this.doc.setDrawColor(...COLORS.border);
      this.doc.setLineWidth(0.3);
      this.doc.roundedRect(MARGIN + 2, this.y - 2, CONTENT_WIDTH - 4, Math.min(cardHeight, 50), 2, 2, 'S');
      
      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      this.doc.text(actor.name, MARGIN + 6, this.y + 2);
      this.y += 4;
      
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(...COLORS.muted);
      const descLines = this.doc.splitTextToSize(actor.description, CONTENT_WIDTH - 12);
      for (const line of descLines) {
        this.doc.text(line, MARGIN + 6, this.y + 2);
        this.y += 3.5;
      }
      this.y += 2;
      
      for (const perm of actor.permissions.slice(0, 8)) {
        this.checkPageBreak(5);
        this.doc.setFontSize(8);
        this.doc.setFont('helvetica', 'normal');
        this.doc.setTextColor(...COLORS.text);
        this.doc.text(`  ✓  ${perm}`, MARGIN + 6, this.y + 1);
        this.y += 4;
      }
      this.y += 4;
    }
  }

  private renderUserStories(srs: ModuleSRS) {
    this.addPage();
    this.sectionTitle(`4. User Stories (${srs.userStories.length})`);
    
    for (const story of srs.userStories) {
      this.checkPageBreak(60);
      
      // Story header card
      this.doc.setFillColor(...COLORS.bg);
      this.doc.roundedRect(MARGIN, this.y - 2, CONTENT_WIDTH, 12, 2, 2, 'F');
      
      // Left accent based on priority
      const pColor = getPriorityColor(story.priority);
      this.doc.setFillColor(...pColor);
      this.doc.rect(MARGIN, this.y - 2, 3, 12, 'F');
      
      // Story ID
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(story.id, MARGIN + 6, this.y + 2);
      
      // Priority badge
      this.drawPriorityBadge(story.priority, MARGIN + 6 + this.doc.getTextWidth(story.id) + 4, this.y + 2);
      
      // Title
      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      this.doc.text(story.title, MARGIN + 6, this.y + 8);
      this.y += 14;
      
      // Actors
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text('Actors: ', MARGIN + 4, this.y);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(story.actors.join(', '), MARGIN + 4 + this.doc.getTextWidth('Actors: '), this.y);
      this.y += 5;
      
      // Description
      this.bodyText(story.description, 4);
      this.y += 3;
      
      // Acceptance Criteria
      this.subSectionTitle('Acceptance Criteria');
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      for (const criteria of story.acceptanceCriteria) {
        const lines = this.doc.splitTextToSize(criteria, CONTENT_WIDTH - 14);
        this.checkPageBreak(lines.length * 4 + 1);
        this.doc.setTextColor(22, 163, 74); // Green
        this.doc.text('✓', MARGIN + 6, this.y);
        this.doc.setTextColor(...COLORS.text);
        for (let i = 0; i < lines.length; i++) {
          this.doc.text(lines[i], MARGIN + 11, this.y);
          this.y += 3.8;
        }
      }
      this.y += 2;
      
      // Business Logic
      if (story.businessLogic.length > 0) {
        this.subSectionTitle('Business Logic');
        this.bulletList(story.businessLogic, 6);
        this.y += 2;
      }
      
      // End-to-End Journey
      if (story.endToEndJourney.length > 0) {
        this.subSectionTitle('End-to-End Journey');
        this.numberedList(story.endToEndJourney, 6);
        this.y += 2;
      }
      
      // Real-World Example box
      this.checkPageBreak(25);
      this.doc.setFillColor(240, 249, 255); // Light blue bg
      const exampleStartY = this.y;
      this.y += 2;
      
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.accent);
      this.doc.text('Real-World Example', MARGIN + 6, this.y + 2);
      this.y += 6;
      
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      const scenarioLines = this.doc.splitTextToSize(story.realWorldExample.scenario, CONTENT_WIDTH - 14);
      for (const line of scenarioLines) {
        this.checkPageBreak(4);
        this.doc.text(line, MARGIN + 6, this.y);
        this.y += 3.8;
      }
      this.y += 1;
      
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      for (let i = 0; i < story.realWorldExample.steps.length; i++) {
        const stepLines = this.doc.splitTextToSize(`${i + 1}. ${story.realWorldExample.steps[i]}`, CONTENT_WIDTH - 14);
        for (const line of stepLines) {
          this.checkPageBreak(4);
          this.doc.text(line, MARGIN + 8, this.y);
          this.y += 3.8;
        }
      }
      this.y += 2;
      
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      const outcomeLines = this.doc.splitTextToSize(`Outcome: ${story.realWorldExample.outcome}`, CONTENT_WIDTH - 14);
      for (const line of outcomeLines) {
        this.checkPageBreak(4);
        this.doc.text(line, MARGIN + 6, this.y);
        this.y += 3.8;
      }
      
      // Draw the example box background (behind the text - we draw it after to know the height)
      const exampleHeight = this.y - exampleStartY + 2;
      // We need to draw the bg first, so we'll use a lighter approach: just draw border
      this.doc.setDrawColor(...COLORS.border);
      this.doc.setLineWidth(0.3);
      this.doc.roundedRect(MARGIN + 2, exampleStartY, CONTENT_WIDTH - 4, exampleHeight, 2, 2, 'S');
      // Left accent for example
      this.doc.setFillColor(...COLORS.accent);
      this.doc.rect(MARGIN + 2, exampleStartY, 2, exampleHeight, 'F');
      
      this.y += 3;
      
      // Related Modules
      if (story.relatedModules.length > 0) {
        this.doc.setFontSize(8);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(...COLORS.muted);
        this.doc.text('Related: ', MARGIN + 4, this.y);
        this.doc.setFont('helvetica', 'normal');
        const related = story.relatedModules.map(r => `${r.module} (${r.relationship})`).join(' • ');
        const relatedLines = this.doc.splitTextToSize(related, CONTENT_WIDTH - 20);
        for (const line of relatedLines) {
          this.doc.text(line, MARGIN + 4 + this.doc.getTextWidth('Related: '), this.y);
          this.y += 3.8;
        }
      }
      
      // Separator between stories
      this.y += 4;
      this.doc.setDrawColor(...COLORS.border);
      this.doc.setLineWidth(0.2);
      this.doc.line(MARGIN + 20, this.y, PAGE_WIDTH - MARGIN - 20, this.y);
      this.y += 6;
    }
  }

  private renderTableSpecs(srs: ModuleSRS) {
    this.addPage();
    this.sectionTitle(`5. Table Specifications (${srs.tableSpecs.length})`);
    
    for (const table of srs.tableSpecs) {
      this.checkPageBreak(30);
      
      // Table name header
      this.doc.setFillColor(...COLORS.dark);
      this.doc.roundedRect(MARGIN, this.y, CONTENT_WIDTH, 8, 1, 1, 'F');
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.white);
      this.doc.text(`${table.schema}.${table.name}`, MARGIN + 4, this.y + 5.5);
      this.y += 10;
      
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(...COLORS.muted);
      this.bodyText(table.description, 2);
      this.y += 2;
      
      // Column headers
      const colWidths = [35, 30, 15, CONTENT_WIDTH - 80];
      const headers = ['Field', 'Type', 'Req', 'Description'];
      
      this.doc.setFillColor(...COLORS.bg);
      this.doc.rect(MARGIN, this.y - 2, CONTENT_WIDTH, 6, 'F');
      this.doc.setFontSize(7);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      
      let xPos = MARGIN + 2;
      headers.forEach((h, i) => {
        this.doc.text(h, xPos, this.y + 2);
        xPos += colWidths[i];
      });
      this.y += 7;
      
      // Rows
      this.doc.setFont('helvetica', 'normal');
      this.doc.setFontSize(7);
      for (const field of table.fields) {
        this.checkPageBreak(5);
        xPos = MARGIN + 2;
        
        this.doc.setFont('courier', 'normal');
        this.doc.setTextColor(...COLORS.dark);
        this.doc.text(field.name.substring(0, 20), xPos, this.y);
        xPos += colWidths[0];
        
        this.doc.setTextColor(...COLORS.accent);
        this.doc.text(field.type.substring(0, 18), xPos, this.y);
        xPos += colWidths[1];
        
        this.doc.setFont('helvetica', 'normal');
        this.doc.setTextColor(field.mandatory ? ...COLORS.critical : ...COLORS.low);
        this.doc.text(field.mandatory ? 'Yes' : 'No', xPos, this.y);
        xPos += colWidths[2];
        
        this.doc.setTextColor(...COLORS.text);
        const desc = field.description + (field.foreignKey ? ` → ${field.foreignKey}` : '');
        const descLines = this.doc.splitTextToSize(desc, colWidths[3] - 4);
        this.doc.text(descLines[0] || '', xPos, this.y);
        
        this.y += 4.5;
        // Light row separator
        this.doc.setDrawColor(...COLORS.border);
        this.doc.setLineWidth(0.1);
        this.doc.line(MARGIN, this.y - 1.5, PAGE_WIDTH - MARGIN, this.y - 1.5);
      }
      this.y += 6;
    }
  }

  private renderBusinessRules(srs: ModuleSRS) {
    this.sectionTitle(`6. Business Rules (${srs.businessRules.length})`);
    
    for (const rule of srs.businessRules) {
      this.checkPageBreak(12);
      
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      this.doc.text(rule.id, MARGIN + 4, this.y);
      
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.dark);
      const ruleLines = this.doc.splitTextToSize(rule.rule, CONTENT_WIDTH - 8);
      this.y += 4;
      for (const line of ruleLines) {
        this.checkPageBreak(4);
        this.doc.text(line, MARGIN + 4, this.y);
        this.y += 3.8;
      }
      
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(...COLORS.muted);
      const ratLines = this.doc.splitTextToSize(`Rationale: ${rule.rationale}`, CONTENT_WIDTH - 8);
      for (const line of ratLines) {
        this.checkPageBreak(4);
        this.doc.text(line, MARGIN + 4, this.y);
        this.y += 3.8;
      }
      this.y += 3;
    }
  }

  private renderIntegrations(srs: ModuleSRS) {
    this.sectionTitle(`7. Integrations (${srs.integrations.length})`);
    
    for (const integration of srs.integrations) {
      this.checkPageBreak(10);
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      this.doc.text(integration.system, MARGIN + 4, this.y);
      
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(` (${integration.type})`, MARGIN + 4 + this.doc.getTextWidth(integration.system), this.y);
      this.y += 4;
      
      this.bodyText(integration.description, 4);
      this.y += 3;
    }
  }

  private renderNFRs(srs: ModuleSRS) {
    if (srs.nonFunctionalRequirements.length === 0) return;
    this.sectionTitle('8. Non-Functional Requirements');
    
    for (const nfr of srs.nonFunctionalRequirements) {
      this.checkPageBreak(8);
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      this.doc.text(`${nfr.id} [${nfr.category}]`, MARGIN + 4, this.y);
      this.y += 4;
      this.bodyText(nfr.requirement, 4);
      this.y += 2;
    }
  }

  public generate(srs: ModuleSRS): jsPDF {
    this.moduleName = srs.moduleName;
    
    // Cover page
    this.drawCoverPage(srs);
    
    // TOC
    this.renderTableOfContents(srs);
    
    // Content sections
    this.renderOverview(srs);
    this.renderScope(srs);
    this.renderActors(srs);
    this.renderUserStories(srs);
    this.renderTableSpecs(srs);
    this.renderBusinessRules(srs);
    this.renderIntegrations(srs);
    this.renderNFRs(srs);
    
    // Add footers to all pages
    this.drawFooters();
    
    return this.doc;
  }
}

export function exportSRSToPdf(srs: ModuleSRS) {
  const builder = new SRSPdfBuilder();
  const doc = builder.generate(srs);
  const fileName = `SRS_${srs.moduleName.replace(/[^a-zA-Z0-9]/g, '_')}_v${srs.version}.pdf`;
  doc.save(fileName);
}

export function exportAllSRSToPdf(modules: { name: string; data: ModuleSRS }[]) {
  // Export each module as a separate PDF
  for (const mod of modules) {
    exportSRSToPdf(mod.data);
  }
}
