import { jsPDF } from 'jspdf';
import { ModuleSRS } from '@/data/srs/rosterSRS';

// Color palette
const COLORS = {
  primary: [30, 64, 175] as [number, number, number],
  primaryLight: [219, 234, 254] as [number, number, number],
  dark: [15, 23, 42] as [number, number, number],
  text: [51, 65, 85] as [number, number, number],
  muted: [100, 116, 139] as [number, number, number],
  border: [203, 213, 225] as [number, number, number],
  bg: [248, 250, 252] as [number, number, number],
  bgCard: [241, 245, 249] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  critical: [220, 38, 38] as [number, number, number],
  high: [234, 88, 12] as [number, number, number],
  medium: [202, 138, 4] as [number, number, number],
  low: [22, 163, 74] as [number, number, number],
  accent: [79, 70, 229] as [number, number, number],
  greenCheck: [22, 163, 74] as [number, number, number],
  exampleBg: [239, 246, 255] as [number, number, number],
};

const MARGIN = 18;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const PAGE_BOTTOM = 280;
const LINE_HEIGHT = 4.5;
const SMALL_LINE = 4;

function getPriorityColor(priority: string): [number, number, number] {
  switch (priority) {
    case 'critical': return COLORS.critical;
    case 'high': return COLORS.high;
    case 'medium': return COLORS.medium;
    case 'low': return COLORS.low;
    default: return COLORS.muted;
  }
}

class SRSPdfBuilder {
  private doc: jsPDF;
  private y: number = 0;
  private moduleName: string = '';

  constructor() {
    this.doc = new jsPDF('p', 'mm', 'a4');
    this.y = MARGIN;
  }

  private ensureSpace(needed: number) {
    if (this.y + needed > PAGE_BOTTOM) {
      this.newPage();
    }
  }

  private newPage() {
    this.doc.addPage();
    this.y = MARGIN;
    this.drawRunningHeader();
  }

  private drawRunningHeader() {
    // Top accent bar
    this.doc.setFillColor(...COLORS.primary);
    this.doc.rect(0, 0, PAGE_WIDTH, 2.5, 'F');

    // Header text
    this.doc.setFontSize(7.5);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.muted);
    this.doc.text(
      `Software Requirements Specification  |  ${this.moduleName}`,
      MARGIN, 9
    );

    // Separator
    this.doc.setDrawColor(...COLORS.border);
    this.doc.setLineWidth(0.25);
    this.doc.line(MARGIN, 11, PAGE_WIDTH - MARGIN, 11);

    this.y = 16;
  }

  private drawAllFooters() {
    const total = this.doc.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      this.doc.setPage(i);
      // Bottom bar
      this.doc.setFillColor(...COLORS.primary);
      this.doc.rect(0, 293, PAGE_WIDTH, 4, 'F');
      // Footer text
      this.doc.setFontSize(7.5);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text('Generated by RosteredAI', MARGIN, 290);
      this.doc.text(`Page ${i} of ${total}`, PAGE_WIDTH - MARGIN, 290, { align: 'right' });
    }
  }

  // ── Primitives ──

  private sectionHeading(title: string) {
    this.ensureSpace(16);
    this.y += 5;

    // Light blue bar with left accent
    this.doc.setFillColor(...COLORS.primaryLight);
    this.doc.roundedRect(MARGIN, this.y - 4.5, CONTENT_WIDTH, 11, 2, 2, 'F');
    this.doc.setFillColor(...COLORS.primary);
    this.doc.rect(MARGIN, this.y - 4.5, 3.5, 11, 'F');

    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...COLORS.primary);
    this.doc.text(title, MARGIN + 7, this.y + 3);
    this.y += 13;
  }

  private subHeading(title: string) {
    this.ensureSpace(10);
    this.y += 2;
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...COLORS.dark);
    this.doc.text(title, MARGIN + 2, this.y);
    this.y += 6;
  }

  private para(text: string, indent = 0) {
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.text);
    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH - indent);
    for (const line of lines) {
      this.ensureSpace(LINE_HEIGHT + 1);
      this.doc.text(line, MARGIN + indent, this.y);
      this.y += LINE_HEIGHT;
    }
  }

  private bullets(items: string[], indent = 4) {
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.text);
    for (const item of items) {
      const lines = this.doc.splitTextToSize(item, CONTENT_WIDTH - indent - 6);
      this.ensureSpace(lines.length * LINE_HEIGHT + 1);
      // Blue dot
      this.doc.setFillColor(...COLORS.primary);
      this.doc.circle(MARGIN + indent + 1, this.y - 1.2, 0.9, 'F');
      this.doc.setTextColor(...COLORS.text);
      for (let i = 0; i < lines.length; i++) {
        this.doc.text(lines[i], MARGIN + indent + 4, this.y);
        this.y += LINE_HEIGHT;
      }
    }
  }

  private numberedSteps(items: string[], indent = 6) {
    for (let idx = 0; idx < items.length; idx++) {
      const textIndent = indent + 8;
      const lines = this.doc.splitTextToSize(
        `${idx + 1}. ${items[idx]}`,
        CONTENT_WIDTH - textIndent
      );
      this.ensureSpace(lines.length * LINE_HEIGHT + 2);

      // Number circle
      const cx = MARGIN + indent + 3;
      const cy = this.y - 0.8;
      this.doc.setFillColor(...COLORS.primary);
      this.doc.circle(cx, cy, 3, 'F');
      this.doc.setFontSize(7.5);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.white);
      const numStr = `${idx + 1}`;
      const numWidth = this.doc.getTextWidth(numStr);
      this.doc.text(numStr, cx - numWidth / 2, cy + 1);

      // Step text
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      for (let i = 0; i < lines.length; i++) {
        this.doc.text(lines[i], MARGIN + textIndent, this.y);
        this.y += LINE_HEIGHT;
      }
      this.y += 0.5;
    }
  }

  private priorityBadge(priority: string, x: number, yPos: number) {
    const color = getPriorityColor(priority);
    this.doc.setFontSize(7);
    this.doc.setFont('helvetica', 'bold');
    const label = priority.toUpperCase();
    const tw = this.doc.getTextWidth(label);
    const badgeW = tw + 5;
    this.doc.setFillColor(...color);
    this.doc.roundedRect(x, yPos - 3.2, badgeW, 4.8, 1.5, 1.5, 'F');
    this.doc.setTextColor(...COLORS.white);
    this.doc.text(label, x + 2.5, yPos);
    return badgeW;
  }

  // ── Sections ──

  private drawCover(srs: ModuleSRS) {
    // Blue full page
    this.doc.setFillColor(...COLORS.primary);
    this.doc.rect(0, 0, PAGE_WIDTH, 297, 'F');

    // White card
    this.doc.setFillColor(...COLORS.white);
    this.doc.roundedRect(16, 38, 178, 210, 5, 5, 'F');

    // Accent strip at top of card
    this.doc.setFillColor(...COLORS.accent);
    this.doc.roundedRect(16, 38, 178, 5, 5, 5, 'F');
    this.doc.setFillColor(...COLORS.accent);
    this.doc.rect(16, 41, 178, 3, 'F');

    // Title
    this.doc.setFontSize(28);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(...COLORS.dark);
    const titleLines = this.doc.splitTextToSize(srs.moduleName, 155);
    let ty = 72;
    for (const line of titleLines) {
      this.doc.text(line, PAGE_WIDTH / 2, ty, { align: 'center' });
      ty += 12;
    }

    // Subtitle
    this.doc.setFontSize(13);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.primary);
    this.doc.text('Software Requirements Specification', PAGE_WIDTH / 2, ty + 4, { align: 'center' });

    // Divider
    this.doc.setDrawColor(...COLORS.border);
    this.doc.setLineWidth(0.4);
    this.doc.line(65, ty + 14, 145, ty + 14);

    // Meta
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(...COLORS.muted);
    const my = ty + 26;
    this.doc.text(`Version ${srs.version}`, PAGE_WIDTH / 2, my, { align: 'center' });
    this.doc.text(`Last Updated: ${srs.lastUpdated}`, PAGE_WIDTH / 2, my + 7, { align: 'center' });

    // Stat boxes
    const stats = [
      { label: 'User Stories', value: srs.userStories.length },
      { label: 'Tables', value: srs.tableSpecs.length },
      { label: 'Rules', value: srs.businessRules.length },
      { label: 'Integrations', value: srs.integrations.length },
    ];
    const bw = 38;
    const gap = 6;
    const totalW = stats.length * bw + (stats.length - 1) * gap;
    const sx = (PAGE_WIDTH - totalW) / 2;
    const sy = my + 22;
    stats.forEach((s, i) => {
      const bx = sx + i * (bw + gap);
      this.doc.setFillColor(...COLORS.bg);
      this.doc.roundedRect(bx, sy, bw, 24, 2, 2, 'F');
      this.doc.setFontSize(18);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      this.doc.text(`${s.value}`, bx + bw / 2, sy + 11, { align: 'center' });
      this.doc.setFontSize(7);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(s.label, bx + bw / 2, sy + 18, { align: 'center' });
    });

    // Cover footer
    this.doc.setFontSize(9);
    this.doc.setTextColor(200, 210, 230);
    this.doc.text('Generated by RosteredAI', PAGE_WIDTH / 2, 262, { align: 'center' });
    const dateStr = new Date().toLocaleDateString('en-AU', {
      year: 'numeric', month: 'long', day: 'numeric',
    });
    this.doc.text(dateStr, PAGE_WIDTH / 2, 268, { align: 'center' });
  }

  private drawTOC(srs: ModuleSRS) {
    this.newPage();
    this.sectionHeading('Table of Contents');
    this.y += 3;

    const items = [
      '1.  Overview & Objectives',
      '2.  Scope',
      '3.  Actors & Permissions',
      `4.  User Stories (${srs.userStories.length})`,
      `5.  Table Specifications (${srs.tableSpecs.length})`,
      `6.  Business Rules (${srs.businessRules.length})`,
      `7.  Integrations (${srs.integrations.length})`,
      '8.  Non-Functional Requirements',
    ];

    this.doc.setFontSize(11);
    for (const item of items) {
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.dark);
      this.doc.text(item, MARGIN + 6, this.y);

      // Dotted leader
      const tw = this.doc.getTextWidth(item);
      this.doc.setDrawColor(...COLORS.border);
      this.doc.setLineDashPattern([0.8, 1.2], 0);
      this.doc.line(MARGIN + 8 + tw, this.y - 0.3, PAGE_WIDTH - MARGIN, this.y - 0.3);
      this.doc.setLineDashPattern([], 0);

      this.y += 8;
    }
  }

  private drawOverview(srs: ModuleSRS) {
    this.newPage();
    this.sectionHeading('1. Overview & Objectives');
    this.para(srs.overview);
    this.y += 4;
    this.subHeading('Objectives');
    this.bullets(srs.objectives);
  }

  private drawScope(srs: ModuleSRS) {
    this.y += 4;
    this.sectionHeading('2. Scope');
    this.subHeading('In Scope');
    this.bullets(srs.scope);
    if (srs.outOfScope.length > 0) {
      this.y += 3;
      this.subHeading('Out of Scope');
      this.bullets(srs.outOfScope);
    }
  }

  private drawActors(srs: ModuleSRS) {
    this.sectionHeading('3. Actors & Permissions');

    for (const actor of srs.actors) {
      // Measure the card height first
      const descLines = this.doc.splitTextToSize(actor.description, CONTENT_WIDTH - 16);
      const permsToShow = actor.permissions.slice(0, 10);
      const cardHeight = 10 + descLines.length * 4 + permsToShow.length * SMALL_LINE + 6;

      this.ensureSpace(cardHeight + 4);

      const cardTop = this.y;

      // Card background + border
      this.doc.setFillColor(...COLORS.bgCard);
      this.doc.roundedRect(MARGIN + 3, cardTop, CONTENT_WIDTH - 6, cardHeight, 3, 3, 'F');
      this.doc.setDrawColor(...COLORS.border);
      this.doc.setLineWidth(0.3);
      this.doc.roundedRect(MARGIN + 3, cardTop, CONTENT_WIDTH - 6, cardHeight, 3, 3, 'S');

      // Left accent on card
      this.doc.setFillColor(...COLORS.primaryLight);
      this.doc.roundedRect(MARGIN + 3, cardTop, 3, cardHeight, 3, 0, 'F');

      this.y = cardTop + 6;

      // Actor name
      this.doc.setFontSize(11);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      this.doc.text(actor.name, MARGIN + 10, this.y);
      this.y += 5;

      // Description (italic)
      this.doc.setFontSize(8.5);
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(...COLORS.muted);
      for (const line of descLines) {
        this.doc.text(line, MARGIN + 10, this.y);
        this.y += 4;
      }
      this.y += 2;

      // Permissions with tick marks
      this.doc.setFontSize(8.5);
      this.doc.setFont('helvetica', 'normal');
      for (const perm of permsToShow) {
        this.doc.setTextColor(...COLORS.primary);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text("'", MARGIN + 10, this.y);
        this.doc.setTextColor(...COLORS.text);
        this.doc.setFont('helvetica', 'normal');
        this.doc.text(perm, MARGIN + 16, this.y);
        this.y += SMALL_LINE;
      }

      this.y = cardTop + cardHeight + 5;
    }
  }

  private drawUserStories(srs: ModuleSRS) {
    this.newPage();
    this.sectionHeading(`4. User Stories (${srs.userStories.length})`);

    for (let si = 0; si < srs.userStories.length; si++) {
      const story = srs.userStories[si];
      this.ensureSpace(55);

      // ── Header bar ──
      this.doc.setFillColor(...COLORS.bg);
      this.doc.roundedRect(MARGIN, this.y, CONTENT_WIDTH, 13, 2, 2, 'F');

      // Priority accent
      const pc = getPriorityColor(story.priority);
      this.doc.setFillColor(...pc);
      this.doc.rect(MARGIN, this.y, 3.5, 13, 'F');

      // Story ID
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(story.id, MARGIN + 7, this.y + 4.5);

      // Priority badge
      const idW = this.doc.getTextWidth(story.id);
      this.priorityBadge(story.priority, MARGIN + 7 + idW + 3, this.y + 4.5);

      // Title
      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      const titleLines = this.doc.splitTextToSize(story.title, CONTENT_WIDTH - 12);
      this.doc.text(titleLines[0], MARGIN + 7, this.y + 10.5);
      this.y += 16;

      // Actors row
      this.doc.setFontSize(8.5);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text('Actors:', MARGIN + 4, this.y);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      this.doc.text(story.actors.join(', '), MARGIN + 4 + this.doc.getTextWidth('Actors: '), this.y);
      this.y += 5;

      // Description
      this.para(story.description, 4);
      this.y += 3;

      // ── Acceptance Criteria ──
      this.subHeading('Acceptance Criteria');
      this.doc.setFontSize(8.5);
      for (const c of story.acceptanceCriteria) {
        const cLines = this.doc.splitTextToSize(c, CONTENT_WIDTH - 16);
        this.ensureSpace(cLines.length * SMALL_LINE + 1);

        // Green check circle
        this.doc.setFillColor(...COLORS.greenCheck);
        this.doc.circle(MARGIN + 7, this.y - 1, 1.5, 'F');
        // White tick approximation (two short lines)
        this.doc.setDrawColor(...COLORS.white);
        this.doc.setLineWidth(0.5);
        this.doc.line(MARGIN + 6.2, this.y - 1, MARGIN + 6.8, this.y - 0.4);
        this.doc.line(MARGIN + 6.8, this.y - 0.4, MARGIN + 7.8, this.y - 1.6);

        this.doc.setFont('helvetica', 'normal');
        this.doc.setTextColor(...COLORS.text);
        for (let i = 0; i < cLines.length; i++) {
          this.doc.text(cLines[i], MARGIN + 12, this.y);
          this.y += SMALL_LINE;
        }
      }
      this.y += 2;

      // ── Business Logic ──
      if (story.businessLogic.length > 0) {
        this.subHeading('Business Logic');
        this.bullets(story.businessLogic, 6);
        this.y += 2;
      }

      // ── End-to-End Journey ──
      if (story.endToEndJourney.length > 0) {
        this.subHeading('End-to-End Journey');
        this.numberedSteps(story.endToEndJourney, 6);
        this.y += 2;
      }

      // ── Real-World Example ──
      this.ensureSpace(30);
      const exTop = this.y;
      this.y += 3;

      this.doc.setFontSize(9.5);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.accent);
      this.doc.text('Real-World Example', MARGIN + 8, this.y + 1);
      this.y += 6;

      // Scenario
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      const scLines = this.doc.splitTextToSize(story.realWorldExample.scenario, CONTENT_WIDTH - 18);
      for (const l of scLines) {
        this.ensureSpace(SMALL_LINE);
        this.doc.text(l, MARGIN + 8, this.y);
        this.y += SMALL_LINE;
      }
      this.y += 1;

      // Steps
      this.doc.setFontSize(8.5);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.text);
      for (let i = 0; i < story.realWorldExample.steps.length; i++) {
        const sLines = this.doc.splitTextToSize(
          `${i + 1}. ${story.realWorldExample.steps[i]}`,
          CONTENT_WIDTH - 20
        );
        this.ensureSpace(sLines.length * SMALL_LINE);
        for (const l of sLines) {
          this.doc.text(l, MARGIN + 10, this.y);
          this.y += SMALL_LINE;
        }
      }
      this.y += 2;

      // Outcome
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      const outLines = this.doc.splitTextToSize(
        `Outcome: ${story.realWorldExample.outcome}`,
        CONTENT_WIDTH - 18
      );
      for (const l of outLines) {
        this.ensureSpace(SMALL_LINE);
        this.doc.text(l, MARGIN + 8, this.y);
        this.y += SMALL_LINE;
      }

      // Draw example box border + accent (after content so height is known)
      const exH = this.y - exTop + 3;
      this.doc.setDrawColor(...COLORS.border);
      this.doc.setLineWidth(0.3);
      this.doc.roundedRect(MARGIN + 3, exTop, CONTENT_WIDTH - 6, exH, 2, 2, 'S');
      this.doc.setFillColor(...COLORS.accent);
      this.doc.rect(MARGIN + 3, exTop, 2.5, exH, 'F');

      this.y += 4;

      // Related modules
      if (story.relatedModules.length > 0) {
        this.doc.setFontSize(8);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(...COLORS.muted);
        this.doc.text('Related:', MARGIN + 4, this.y);
        this.doc.setFont('helvetica', 'normal');
        const relText = story.relatedModules.map(r => `${r.module} (${r.relationship})`).join('  |  ');
        const relLines = this.doc.splitTextToSize(relText, CONTENT_WIDTH - 22);
        const labelW = this.doc.getTextWidth('Related: ');
        for (const l of relLines) {
          this.doc.text(l, MARGIN + 4 + labelW, this.y);
          this.y += SMALL_LINE;
        }
      }

      // Story separator
      this.y += 4;
      if (si < srs.userStories.length - 1) {
        this.doc.setDrawColor(...COLORS.border);
        this.doc.setLineWidth(0.15);
        this.doc.line(MARGIN + 30, this.y, PAGE_WIDTH - MARGIN - 30, this.y);
        this.y += 6;
      }
    }
  }

  private drawTableSpecs(srs: ModuleSRS) {
    this.newPage();
    this.sectionHeading(`5. Table Specifications (${srs.tableSpecs.length})`);

    for (const table of srs.tableSpecs) {
      this.ensureSpace(25);

      // Table name header bar
      this.doc.setFillColor(...COLORS.dark);
      this.doc.roundedRect(MARGIN, this.y, CONTENT_WIDTH, 8, 1.5, 1.5, 'F');
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.white);
      this.doc.text(`${table.schema}.${table.name}`, MARGIN + 5, this.y + 5.5);

      // Field count badge
      const countLabel = `${table.fields.length} fields`;
      const countW = this.doc.getTextWidth(countLabel) + 5;
      this.doc.setFillColor(...COLORS.accent);
      this.doc.roundedRect(PAGE_WIDTH - MARGIN - countW - 3, this.y + 1.5, countW, 5, 1.5, 1.5, 'F');
      this.doc.setFontSize(7);
      this.doc.text(countLabel, PAGE_WIDTH - MARGIN - countW - 0.5, this.y + 5);
      this.y += 11;

      // Description
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(...COLORS.muted);
      const dLines = this.doc.splitTextToSize(table.description, CONTENT_WIDTH - 4);
      for (const l of dLines) {
        this.doc.text(l, MARGIN + 2, this.y);
        this.y += 3.5;
      }
      this.y += 2;

      // Column headers
      const cw = [36, 28, 14, CONTENT_WIDTH - 78];
      const headers = ['Field', 'Type', 'Req', 'Description'];

      this.doc.setFillColor(...COLORS.primaryLight);
      this.doc.rect(MARGIN, this.y - 2, CONTENT_WIDTH, 6, 'F');
      this.doc.setFontSize(7.5);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      let xp = MARGIN + 2;
      headers.forEach((h, i) => {
        this.doc.text(h, xp, this.y + 1.5);
        xp += cw[i];
      });
      this.y += 7;

      // Rows
      let alt = false;
      for (const field of table.fields) {
        this.ensureSpace(5.5);
        if (alt) {
          this.doc.setFillColor(...COLORS.bg);
          this.doc.rect(MARGIN, this.y - 2.5, CONTENT_WIDTH, 5, 'F');
        }
        alt = !alt;

        xp = MARGIN + 2;
        this.doc.setFontSize(7.5);
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(...COLORS.dark);
        this.doc.text(field.name.substring(0, 22), xp, this.y);
        xp += cw[0];

        this.doc.setFont('helvetica', 'normal');
        this.doc.setTextColor(...COLORS.accent);
        this.doc.text(field.type.substring(0, 18), xp, this.y);
        xp += cw[1];

        const reqColor = field.mandatory ? COLORS.critical : COLORS.low;
        this.doc.setTextColor(...reqColor);
        this.doc.setFont('helvetica', 'bold');
        this.doc.text(field.mandatory ? 'Yes' : 'No', xp, this.y);
        xp += cw[2];

        this.doc.setFont('helvetica', 'normal');
        this.doc.setTextColor(...COLORS.text);
        const desc = field.description + (field.foreignKey ? ` -> ${field.foreignKey}` : '');
        const dl = this.doc.splitTextToSize(desc, cw[3] - 2);
        this.doc.text(dl[0] || '', xp, this.y);

        this.y += 5;
      }
      this.y += 6;
    }
  }

  private drawBusinessRules(srs: ModuleSRS) {
    this.sectionHeading(`6. Business Rules (${srs.businessRules.length})`);

    for (const rule of srs.businessRules) {
      this.ensureSpace(14);

      // Rule ID badge
      this.doc.setFontSize(7.5);
      this.doc.setFont('helvetica', 'bold');
      const idW = this.doc.getTextWidth(rule.id) + 4;
      this.doc.setFillColor(...COLORS.primaryLight);
      this.doc.roundedRect(MARGIN + 3, this.y - 3, idW, 5, 1.5, 1.5, 'F');
      this.doc.setTextColor(...COLORS.primary);
      this.doc.text(rule.id, MARGIN + 5, this.y);
      this.y += 4;

      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(...COLORS.dark);
      const rLines = this.doc.splitTextToSize(rule.rule, CONTENT_WIDTH - 8);
      for (const l of rLines) {
        this.ensureSpace(LINE_HEIGHT);
        this.doc.text(l, MARGIN + 5, this.y);
        this.y += LINE_HEIGHT;
      }

      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'italic');
      this.doc.setTextColor(...COLORS.muted);
      const ratLines = this.doc.splitTextToSize(`Rationale: ${rule.rationale}`, CONTENT_WIDTH - 8);
      for (const l of ratLines) {
        this.ensureSpace(SMALL_LINE);
        this.doc.text(l, MARGIN + 5, this.y);
        this.y += SMALL_LINE;
      }
      this.y += 3;
    }
  }

  private drawIntegrations(srs: ModuleSRS) {
    this.sectionHeading(`7. Integrations (${srs.integrations.length})`);

    for (const integ of srs.integrations) {
      this.ensureSpace(12);

      this.doc.setFontSize(9.5);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.dark);
      this.doc.text(integ.system, MARGIN + 4, this.y);

      // Type badge
      const sysW = this.doc.getTextWidth(integ.system);
      this.doc.setFontSize(7);
      this.doc.setFont('helvetica', 'normal');
      const typeLabel = integ.type;
      const typeW = this.doc.getTextWidth(typeLabel) + 4;
      this.doc.setFillColor(...COLORS.bg);
      this.doc.roundedRect(MARGIN + 6 + sysW, this.y - 3, typeW, 4.5, 1.5, 1.5, 'F');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(typeLabel, MARGIN + 8 + sysW, this.y);
      this.y += 5;

      this.para(integ.description, 4);
      this.y += 3;
    }
  }

  private drawNFRs(srs: ModuleSRS) {
    if (srs.nonFunctionalRequirements.length === 0) return;
    this.sectionHeading('8. Non-Functional Requirements');

    for (const nfr of srs.nonFunctionalRequirements) {
      this.ensureSpace(10);

      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(...COLORS.primary);
      this.doc.text(`${nfr.id}`, MARGIN + 4, this.y);

      // Category badge
      const idW = this.doc.getTextWidth(nfr.id);
      this.doc.setFontSize(7);
      const catW = this.doc.getTextWidth(nfr.category) + 4;
      this.doc.setFillColor(...COLORS.bg);
      this.doc.roundedRect(MARGIN + 6 + idW, this.y - 3, catW, 4.5, 1.5, 1.5, 'F');
      this.doc.setTextColor(...COLORS.muted);
      this.doc.text(nfr.category, MARGIN + 8 + idW, this.y);
      this.y += 5;

      this.para(nfr.requirement, 4);
      this.y += 2;
    }
  }

  // ── Public ──

  public generate(srs: ModuleSRS): jsPDF {
    this.moduleName = srs.moduleName;

    this.drawCover(srs);
    this.drawTOC(srs);
    this.drawOverview(srs);
    this.drawScope(srs);
    this.drawActors(srs);
    this.drawUserStories(srs);
    this.drawTableSpecs(srs);
    this.drawBusinessRules(srs);
    this.drawIntegrations(srs);
    this.drawNFRs(srs);
    this.drawAllFooters();

    return this.doc;
  }
}

export function exportSRSToPdf(srs: ModuleSRS) {
  const builder = new SRSPdfBuilder();
  const doc = builder.generate(srs);
  const fileName = `SRS_${srs.moduleName.replace(/[^a-zA-Z0-9]/g, '_')}_v${srs.version}.pdf`;
  doc.save(fileName);
}

export function exportAllSRSToPdf(modules: { name: string; data: ModuleSRS }[]) {
  for (const mod of modules) {
    exportSRSToPdf(mod.data);
  }
}
